### PR TITLE
[Fixes #550] Add PropType checking to Menu's position and update docs

### LINKED ISSUE #550: IconMenu positioning not working since 1.0.0?
Not sure if I've missed something but the `IconMenu` demo (http://react-toolbox.com/#/components/menu) seems broken, the menu does impact the flow of DOM elements when closed (eg. hidden but still there in the DOM), shouldn't the position be absolute-like?

Also tried to play with the `position` attr/prop, and nothing changes.

Is it a regression or has it always behaved like this? Is this open for a PR?

### PR DESCRIPTION
**Pull request by Danno040**
I got burned by Issue #550 when upgrading to 1.0.0. The position property on Menu got moved from dashes to camelCase, but the docs weren't updated.

This PR updates the docs, and adds a PropType check on position.

### CODE REVIEW

File: components/menu/Menu.js [hunk 1]
```diff
@@ -25,7 +25,10 @@ const factory = (MenuItem) => {
       onSelect: PropTypes.func,
       onShow: PropTypes.func,
       outline: PropTypes.bool,
-      position: PropTypes.string,
+      position: PropTypes.oneOf([
```
Comment (jingyuyao) [inline components/menu/Menu.js]: Wouldn't it be better to do something like this?
```
position: PropTypes.oneOf(Object.keys(POSITION).map(key => POSITION[key])),
```

Comment (Danno040) [inline components/menu/Menu.js]: I wasn't sure the support for Object.keys, so I hesitated to use it. Its ES5, so I updated the code to use your snippet.

**Comment by javivelasco** [comment]
Wow, sorry about that!
