### PR TITLE
fix(Dropdown):  fix Dropdown not closing when click , resolves #1865

### LINKED ISSUE #1865: Dropdown not closing
Almost same issue as https://github.com/react-toolbox/react-toolbox/issues/1475 but the issue was closed without a good resolution (the only difference being that for me active is not getting switched when an item is clicked but the value is)
Conflicts with any versions of postcss-loader are not documented so this is still a bug that should be fixed.

### PR DESCRIPTION
**Pull request by rezak-otmani**
Close #1865

Add onClick to handle dropdown closing

### CODE REVIEW

**Comment by devzsolt** [comment]
@rezak-otmani when can we see your fix released? 2.0.0-beta.12/npm 2.0.0-beta.13 still doesn't have it. Thanks!

File: components/dropdown/Dropdown.js [hunk 1]
```diff
@@ -180,7 +180,8 @@ const factory = (Input) => {
         <li
           key={idx}
           className={className}
-          onMouseDown={!item.disabled && this.handleSelect.bind(this, item[valueKey])}
+          onMouseDown={!item.disabled}
+          onClick={this.handleSelect.bind(this, item[valueKey])}
```
Comment (rubenmoya) [inline components/dropdown/Dropdown.js]: I have the feeling that `onMouseDown` is doing nothing since it's expecting a function, and `onClick` is handling the click event even if the dropdown is disabled.

Since you can't open open the dropdown if it's disabled it makes no sense to have that check in the values of the dropdown, can you remove it?

Can you check if it works as expected with the dropdown disabled?

**Review by rubenmoya — CHANGES_REQUESTED** [review]

**Comment by jacargentina** [comment]
@rezak-otmani any news? I've tested this inside a Dialog and is not working fine

**Comment by rezak-otmani** [comment]
I'm sorry for my late response, I change the PR using onClick directly I think that makes sense

**Comment by martinkomitsky** [comment]
@rubenmoya Can you merge and publish this small fix? We all need this a lot, it's only 1 line diff

**Review by rubenmoya — APPROVED** [review]

**Comment by rubenmoya** [comment]
Thank you for the PR @rezak-otmani!

**Comment by alexhisen** [comment]
Any update on publishing an updated release with this fix?

**Comment by alexhisen** [comment]
@rubenmoya can you please publish a new version to npm.

**Comment by michaelangeloJetBlack** [comment]
@rubenmoya Sorry to ping you on this again, any chance you can publish a new release 🙏🏻

**Comment by alexhisen** [comment]
@michaelangeloJetBlack, @rubenmoya  The current repo has some major bugs and breaking changes, so it cannot just be published to npm. It can be published, perhaps as 3.0, after merging PRs #1920, #1921, #1922 and #1923.
